branches:
  only:
  - master
  - release
  - travis_dbg
env:
  global:
  - secure: fIpwqTk0CaukDz2gGEW8R7Pwa+dLPuPA5hcDm5d5vuqNH2FA02oX09fUrqZWPBlM79ve6UmRTt0TNM2kKCMuZQB175dY/CCPHO22aOw+uMP7ywFkq2FIK8+1qvkTUwWmNsA+sHTMrdmNBM4unguwBq8v3627dik8FAOAkqVWtUI=
  - secure: IaL7OXZlR7H/9CiAXik2i8sj83EflxBHhGncamJ4DmyzanXHB4djE65skBLueLe5uZTI2uEVDkasYSfeUUQoEXkawHW4P17yiDG23i+oBJGORUH4RUY0U/cWRKC6mb1ESKYmMBahuHXxg9NuwsaMQWYti+KILUh5xaHDZVedCCg=
  - secure: kUYIHVHjuB5GIym8Wv1B32zn6rcTZ+ZPX3Wfu4zZ+OuTWMv3/hCJpsV0IexmTbb/1erpO+r3MrKuwbzSmfMI1Bm7AF1ZrihjnSgR7a7Diae72zFRIGzDFoHAxQT6+8uvPDJsz/3Cj1tS+3IGQCo38SwxFnp3xFKSt6yDtIN3XJU=
  - secure: u1H7J1NyT2RLDzo9M2A8rCEc9YAw/pg4j6uPimC9d85vIpcDDwN6FpZ8NbOEPKdy0M3uComObWv7b00FQvEB2d7WdRlRRIjlbSqwtiQQj0JjOWyrPdxUQvNt2Hp1G3du5o/beqJ7f8EuC0ZsSlSnI606nf7iqKHV8EqlCFJsu9g=
  - secure: i5X9JGrW04KMnNkqs/XN0SOUFYuwVPTdZZVYQfdoWNYUyRE8c8VC8wkRyQzJoR08iBK1whnaY09NmdPS5wO/jBdwXNZjWBUEsL1jFd+fOtxAnJ1tlopVIdGxVAf1cs3laLwKlRmt0BjbAJqWEYAnN4+QUrCkU6zFfb8j08SIDyQ=
before_install:
- openssl aes-256-cbc -K $encrypted_e836d0488b25_key -iv $encrypted_e836d0488b25_iv
  -in etc/gpg.enc -out etc/gpg -d
- openssl aes-256-cbc -K $encrypted_e836d0488b25_key -iv $encrypted_e836d0488b25_iv
  -in etc/autobot.enc -out etc/autobot -d
- eval "$(ssh-agent)"
- gpg --import etc/gpg
- chmod 600 etc/autobot
- ssh-add etc/autobot
- git config --global user.name "Build Bot"
- git config --global user.email "buildbot@btrplace.org"
- git remote add deploy git@github.com:btrplace/scheduler.git
- export MAVEN_OPTS=-Xmx512m
- mkdir /tmp/m2_repo
install:
- bin/cache.sh get /tmp/cache btrplace/travis-cache
- mvn -Dmaven.repo.local=/tmp/cache -Dgpg.passphrase=${GPG_PASSPHRASE} install -DskipTests
- bin/cache.sh push /tmp/cache
jdk:
- oraclejdk8
language: java
notifications:
  email:
    on_failure: always
    on_success: always
    recipients:
    - btrplace-ci@googlegroups.com
script: ./bin/build.sh
