#!/bin/bash 

FILE="$1"

ENERGY=0
TIME=0

for line in `tail -n +4 $FILE`; do
    POWER=`echo "$line" | cut -d',' -f 2`
    ENERGY=`bc <<< "$ENERGY + $POWER"`
    TIME=$((TIME+1))
done

echo "Completion time: $TIME"
echo "Cummulative power: $ENERGY"
echo "Energy consumed: `bc <<< "$ENERGY/$TIME"`"
